name: build themes


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: 'build'
        timeout-minutes: 400
        run: python ./scripts/build_themes.py
      - name: 'Commit'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if ! [[ -z $(git status -s) ]]; then
           git add *
           git commit -m "build themes"
          fi
      - name: 'Push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
